#@(#)________________________________________________________________
#@(#) Copyright(C) 2025 fnyxzz
#@(#) All rights reserved.
#@(#)
#@(#) Use and distribution of this software and its source code
#@(#) are governed by the terms and conditions of the
#@(#) fnyxzz lisence ("LICENSE.TXT")
#@(#) ----------------------------------------------------------------
#@(#) Name          :       config.yaml
#@(#) Author        :       Ketil Heggtveit
#@(#) ----------------------------------------------------------------
#@(#) Description   :       Configuration file for the nmapwrap 
#@(#)                       program 
#@(#) Default Location:     /opt/nmapwrap
#@(#) ----------------------------------------------------------------
#  +  ---------------------------------------------------------------- 
#  +  Application definition 
#  +  ---------------------------------------------------------------- 
app:
  name: nmapwrap
  version: 1.0.0
  environment: production

#  +  ---------------------------------------------------------------- 
#  +  local directories environment 
#  +  ---------------------------------------------------------------- 
installation:
  root:     /opt/nmapwrap
  nmapdata: /opt/nmapwrap/data
  export:   /opt/nmapwrap/export 
#  +  ---------------------------------------------------------------- 
#  +  uid 
#  +  ---------------------------------------------------------------- 
uid: 
  username: ketilheggtveit
  accessrights: "0o755"

#  +  ---------------------------------------------------------------- 
#  +  Logging configuration 
#  +  ---------------------------------------------------------------- 
logging:
  level: DEBUG
  file: nmapwrap.log
  dir:  /opt/nmapwrap/logs 

#  +  ---------------------------------------------------------------- 
#  +  sources 
#  +  ---------------------------------------------------------------- 
sources:
   nmap: /opt/homebrew/bin/nmap 
   rsync: /usr/bin/rsync 
   ports: ports.yaml
