#@(#)________________________________________________________________
#@(#) Copyright(C) 2025 fnyxzz
#@(#) All rights reserved.
#@(#)
#@(#) Use and distribution of this software and its source code
#@(#) are governed by the terms and conditions of the
#@(#) fnyxzz lisence ("LICENSE.TXT")
#@(#) ----------------------------------------------------------------
#@(#) Name          :       internal_full.yaml
#@(#) Author        :       Ketil Heggtveit
#@(#) ----------------------------------------------------------------
#@(#) Description   :       Configuration file for the client 
#@(#)               :       home
#@(#) Default Location:     
#@(#) ----------------------------------------------------------------
#  +  ---------------------------------------------------------------- 
#  +  Client information 
#  +  ---------------------------------------------------------------- 
client:
  name: internal_full
  clienthome : /opt/nmapwrap/data/
  clientip: 10.0.0.0/24 

#  +  ---------------------------------------------------------------- 
#  +  nmap discover settings 
#  +  Called Ping scan. This detects host on the network. 
#  +  If the ICMP ping does not discover the host, then 
#  +  Nmap will run a tcp ping on the spesified ports. 
#  +  Add/delete ports which fits your environment. 
#  +  NB! important! host may be online if none of these ports are 
#  +  reachable. Should always know your environment before scanning
#  +  Change ports to suite your needs. 
#  +  ---------------------------------------------------------------- 
nmap_discoverycfg:
  order: 1 
  scan-type: discovery
  suffix: ping
  genonlinehosts: True
  scanflag: -sn -n -PE 
  max-hostgroup: 150 
  max-retries: 4 
  min-rtt-timeout: 100ms 
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms 
  min-rate: 450 
  max-rate: 15000 
  max-rtt-timeout: 50ms 
  reports: -oA 
  ports:  -PS21-23,25-26,53,80-81,110-111,113,135,139,143,443,445,465
          ,514-515,587,993,995,1025-1026,1433,3306,3389,5060,5432,5900
          ,6000,6881,8000,8008,8080,8443

#  +  ----------------------------------------------------------------
#  +  nmap Normal scan 
#  +  we scan the top 4000 ports 
#  +  ----------------------------------------------------------------
nmap_normal:
  order: 2
  scan-type: normal
  suffix: tcp
  scanflag: -sS -n
  max-hostgroup: 150
  max-retries: 4
  min-rtt-timeout: 100ms
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms
  min-rate: 450
  max-rate: 15000
  max-rtt-timeout: 50ms
  reports: -oA
  top-ports: 500

#  +  ----------------------------------------------------------------
#  +  nmap TOP 1000 ports 
#  +  We scan top 1000 ports 
#  +  
#  +  ----------------------------------------------------------------
nmap_top1000:
  order: 3
  scan-type: top1000
  suffix: tcp
  scanflag: -sS -n
  max-hostgroup: 150
  max-retries: 4
  min-rtt-timeout: 100ms
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms
  min-rate: 450
  max-rate: 15000
  max-rtt-timeout: 50ms
  reports: -oA
  ports: -p 1-1024


#  +  ----------------------------------------------------------------
#  +  nmap Full
#  +  We scan ALL 65535 ports 
#  +  
#  +  ----------------------------------------------------------------
nmap_Full:
  order: 4
  scan-type: full
  suffix: tcp
  scanflag: -sS -n
  max-hostgroup: 150
  max-retries: 4
  min-rtt-timeout: 100ms
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms
  min-rate: 450
  max-rate: 15000
  max-rtt-timeout: 50ms
  reports: -oA
  ports: -p- 
