#@(#)________________________________________________________________
#@(#) Copyright(C) 2025 fnyxzz
#@(#) All rights reserved.
#@(#)
#@(#) Use and distribution of this software and its source code
#@(#) are governed by the terms and conditions of the
#@(#) fnyxzz lisence ("LICENSE.TXT")
#@(#) ----------------------------------------------------------------
#@(#) Name          :       TestClient.yaml
#@(#) Author        :       Ketil Heggtveit
#@(#) ----------------------------------------------------------------
#@(#) Description   :       Configuration file for the client 
#@(#)               :       home
#@(#) Default Location:     
#@(#) ----------------------------------------------------------------
#  +  ---------------------------------------------------------------- 
#  +  Client information 
#  +  ---------------------------------------------------------------- 
client:
  name: TestClient
  clienthome : /opt/nmapwrap/data/
  clientip: 10.0.0.0/24 

#  +  ---------------------------------------------------------------- 
#  +  nmap discover settings 
#  +  ---------------------------------------------------------------- 
nmap_discoverycfg:
  order: 1
  scan-type: discovery
  scanflag: -sS -n -PE
  max-hostgroup: 150
  max-retries: 4
  min-rtt-timeout: 100ms
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms
  min-rate: 450
  max-rate: 15000
  max-rtt-timeout: 50ms
  reports: -oA
  ports: -p 22

   
#  +  ---------------------------------------------------------------- 
#  +  nmap Full settings 
#  +  ---------------------------------------------------------------- 
nmap_fullcfg:
  order: 2
  scan-type: full
  scanflag: -sS -n -PE
  max-hostgroup: 150 
  max-retries: 4 
  min-rtt-timeout: 100ms 
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms 
  min-rate: 450 
  max-rate: 15000 
  max-rtt-timeout: 50ms 
  reports: -oA
  ports: -p 1-1023 


#  +  ---------------------------------------------------------------- 
#  +  nmap top 2096 ports 
#  +  ---------------------------------------------------------------- 
nmap_top2096:
  order: 3
  scan-type: top2000
  scanflag: -sS -n -PE
  max-hostgroup: 150 
  max-retries: 4 
  min-rtt-timeout: 100ms 
  initial-rtt-timeout: 500ms
  scan-delay: 2ms
  max-scan-delay: 20ms 
  min-rate: 450 
  max-rate: 15000 
  max-rtt-timeout: 50ms 
  reports: -oA
  top-ports: 2096


